version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      #      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/configs/enterprise-search.yml:/usr/share/elasticsearch/config/enterprise-search.yml
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - esnet

  fscrawler:
    build: fscrawler
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - JOB_NAME=lode
    ports:
      - 18080:8080
    volumes:
      - ./fscrawler/configs/lode:/usr/share/fscrawler/config/lode
      - ./fscrawler/configs/_default/7/_settings.json:/usr/share/fscrawler/config/_default/7/_settings.json
      - ./watchfolder:/usr/share/fscrawler/data/:ro
    networks:
      - esnet

  webapp:
    build: web
    ports:
      - "4000:80"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./watchfolder:/www/static

      # enable when doing local development
      # run the following command locally:
      #   ng build --output-path ./dist --base-href "/" --prod --watch
      - ./web/dist:/www/web

    networks:
      - esnet

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.2.1
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - XPACK_MONITORING_ENABLED=false
#    networks:
#      - esnet

  storage:
    image: minio/minio
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9000/minio/health/ready || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - ./watchfolder:/data/documents
      - ./thumbnails:/data/thumbnails
    environment:
      - MINIO_WORM=on
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: gateway nas /data

  storageconfig:
    build: storageconfig
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    depends_on:
      storage:
        condition: service_healthy


volumes:
  esdata:
    driver: local
  lodethumbs:
    driver: local

networks:
  esnet:
