---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: processor
  namespace: lodestone
  labels:
    k8s-app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: processor
  template:
    metadata:
      labels:
        k8s-app: processor
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 30
      containers:
      - image: analogj/lodestone:processor
        imagePullPolicy: Always
        name: processor
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: RABBITMQ_USER
          value: "lodestone"
        - name: RABBITMQ_PASS
          value: "lodestone"
        - name: LS_ELASTICSEARCH_HOST
          value: "elasticsearch"
        - name: LS_ELASTICSEARCH_PORT
          value: "9200"
        - name: LS_RABBITMQ_HOST
          value: rabbitmq
        - name: LS_RABBITMQ_PORT
          value: 5672
        - name: LS_STORAGE_HOST
          value: storage
        - name: LS_STORAGE_PORT
          value: "9000"
        - name: LS_TIKA_HOST
          value: "tika"
        - name: LS_TIKA_PORT
          value: "9998"
        securityContext:
          allowPrivilegeEscalation: false
