---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: processor
  namespace: lodestone
  labels:
    k8s-app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: processor
  template:
    metadata:
      labels:
        k8s-app: processor
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 30
      containers:
      - image: analogj/lodestone:processor
        imagePullPolicy: Always
        name: processor
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: RABBITMQ_USER
          value: "lodestone"
        - name: RABBITMQ_PASS
          value: "lodestone"
        securityContext:
          allowPrivilegeEscalation: false
