---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: lodestone
  labels:
    k8s-app: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      k8s-app: rabbitmq
  template:
    metadata:
      labels:
        k8s-app: rabbitmq
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: Always
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "lodestone"
        - name: RABBITMQ_DEFAULT_PASS
          value: "lodestone"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        securityContext:
          allowPrivilegeEscalation: false
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: lodestone
  labels:
    k8s-app: rabbitmq
spec:
  selector:
    k8s-app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: mgmt
